### ISSUE TITLE
Wie Öffnen?

### ISSUE THREAD

**Issue by RegularTom91** [tfaehse/DashcamCleaner#72]
Hallo. Ich habe soweit alles nach Anleitung auf meinen Desktop bekommen.

Jetzt habe ich ein bescheidenes Problem und mir ist es unangenehm zu fragen, jedoch...wie öffne ich nun das Tool?

Gibt es dazu einen Code oder eine .exe die ich nicht finde?
Im Reiter Usage ist für mich als Laie keine verwertbare Information gegeben. 

LG, Tom

**Comment by joshinils** [comment]
da ich weder die gui version benutze, noch windows, hier ein paar ideen von mir:

* doppelclick auf die main.py datei
* im terminal den ordner `DashcamCleaner/dashcamcleaner/` öffnen und `main.py` eingeben, enter drücken, das terminal muss offen bleiben.

**Comment by RegularTom91** [comment]
Doppelclick auf die Datei öffnet nur ein Fenster, was blitzartig verschwindet. Nichts kommt danach.

Zweiter Punkt geht bei der Windows Powsershell nicht.

Dritter Punkt, kommt diese Meldung:

PS C:\Users\Calyx\Desktop\Dashblur\DashcamCleaner\dashcamcleaner> python main.py
Traceback (most recent call last):
  File "C:\Users\Calyx\Desktop\Dashblur\DashcamCleaner\dashcamcleaner\main.py", line 260, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\Calyx\Desktop\Dashblur\DashcamCleaner\dashcamcleaner\main.py", line 37, in __init__
    self.blur_wrapper = self.setup_blurrer()
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Calyx\Desktop\Dashblur\DashcamCleaner\dashcamcleaner\main.py", line 58, in setup_blurrer
    blur_wrapper = qtVideoBlurWrapper(weights_name, init_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Calyx\Desktop\Dashblur\DashcamCleaner\dashcamcleaner\src\qt_wrapper.py", line 28, in __init__
    QThread.__init__(self)
TypeError: VideoBlurrer.__init__() missing 2 required positional arguments: 'weights_name' and 'parameters'

Windows 10.

**Comment by nils8107** [comment]
Hello/ Hallo

I have installed everything on my new PC. Win11, 13700k, RTX4090

I get this error when I want to start the GUI:

Any advice please?

(py39) C:\Users\Nils\OneDrive\Desktop\Dashcamcleaner\dashcamcleaner>python main.py
Traceback (most recent call last):
  File "C:\Users\Nils\OneDrive\Desktop\Dashcamcleaner\dashcamcleaner\main.py", line 260, in <module>
    window = MainWindow()
  File "C:\Users\Nils\OneDrive\Desktop\Dashcamcleaner\dashcamcleaner\main.py", line 37, in __init__
    self.blur_wrapper = self.setup_blurrer()
  File "C:\Users\Nils\OneDrive\Desktop\Dashcamcleaner\dashcamcleaner\main.py", line 58, in setup_blurrer
    blur_wrapper = qtVideoBlurWrapper(weights_name, init_params)
  File "C:\Users\Nils\OneDrive\Desktop\Dashcamcleaner\dashcamcleaner\src\qt_wrapper.py", line 28, in __init__
    QThread.__init__(self)
TypeError: __init__() missing 2 required positional arguments: 'weights_name' and 'parameters'

**Comment by RegularTom91** [comment]
>>> python.exe main.py 

das ist alles und es läuft.
